### PR TITLE
Topics organized by time

### PR DESCRIPTION
**Pull request by MarPinPar**
Because the order is defined by the time, each topic is separated by five minutes with the next one, so if a new one has to be between them, there is a time margin for it to be placed.
There is a .txt file that contains the order of the topics and their corresponding times. If you think that it might be useful (i think it is because everyone can check the exact time to better organize their contributions), I can add it in another PR

### CODE REVIEW

**Review by juanbono — CHANGES_REQUESTED** [review]
I think we should organize topics by complexity, not time. Because it is not natural to see a complex topic first and a simple one like if statements or numeric operations later only because they were added at a later time

**Comment by MarPinPar** [comment]
I believe you misunderstood my message
Topics are organized by time because of the framework format that is being used for the webpage. That is why all the modifications are the dates of the files

**Comment by MarPinPar** [comment]
This is the order I designed. I already talked to Francisco asking about this, but please check it out:

hello world - 12:00
assert - 12:05
comments - 12:10
variables - 12:15
naming conventions - 12:20
felt252 - 12:25
integers - 12:26
# strings - 12:30 #
arrays - 12:35
structs - 12:40
enums - 12:45
tuples - 12:50
dictionaries - 12:51
functions - 12:55
if / else - 13:00
loops - 13:05
# recursion - 13:10 #
ownership - 13:15
snapshots  - 13:20
pattern matching - 13:25
generics - 13:30
testing - 13:35
# error_handling - 13:40 #
operator overloading - 13:45
zeroable - 13:50
# keywords - 13:55 #

(Topics marked with "#" are still pending of approval of the PR so its time is not updated yet in this PR)

**Comment by unbalancedparentheses** [comment]
> I believe you misunderstood my message What you're saying is exactly what this PR aims to solve. Topics are organized "by time" because of the framework format that is being used for the webpage. That is why all the modifications are the dates of the files

@juanbono I think you might have not understaood what @MarPinPar said. I think you're right. Let's fix it.

**Pull request merged**
